from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput
from kivy.uix.button import Button


class MiniCalculatorApp(BoxLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.orientation = 'vertical'

        # Title
        self.add_widget(Label(text="~~~~ Mini Calculator ~~~~", font_size="24sp"))

        # Input for the first number
        self.add_widget(Label(text="Enter the first number:"))
        self.num1_input = TextInput(multiline=False, input_filter="float")
        self.add_widget(self.num1_input)

        # Input for the second number
        self.add_widget(Label(text="Enter the second number:"))
        self.num2_input = TextInput(multiline=False, input_filter="float")
        self.add_widget(self.num2_input)

        # Choice buttons
        self.add_widget(Label(text="Select operation:"))
        buttons_layout = BoxLayout(size_hint_y=None, height=50)

        for operation, symbol in [("Add", "+"), ("Subtract", "-"), ("Multiply", "*"), ("Divide", "/")]:
            btn = Button(text=f"{operation} ({symbol})")
            btn.bind(on_press=self.calculate)
            buttons_layout.add_widget(btn)

        self.add_widget(buttons_layout)

        # Result label
        self.result_label = Label(text="")
        self.add_widget(self.result_label)

    def calculate(self, instance):
        try:
            num1 = float(self.num1_input.text)
            num2 = float(self.num2_input.text)
            operation = instance.text.split()[0].lower()

            if operation == "add":
                result = num1 + num2
            elif operation == "subtract":
                result = num1 - num2
            elif operation == "multiply":
                result = num1 * num2
            elif operation == "divide":
                if num2 == 0:
                    self.result_label.text = "Error: Division by zero!"
                    return
                result = num1 / num2
            else:
                self.result_label.text = "Invalid operation!"
                return

            self.result_label.text = f"Result: {result}"
        except ValueError:
            self.result_label.text = "Please enter valid numbers!"


class CalculatorApp(App):
    def build(self):
        return MiniCalculatorApp()


if __name__ == "__main__":
    CalculatorApp().run()
